# Generated by Django 2.2.14 on 2020-08-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='title',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
