# Generated by Django 2.2.14 on 2020-08-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='title',
        ),
    ]
