# Generated by Django 2.2.14 on 2020-08-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='title',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
