# Generated by Django 2.2.14 on 2020-08-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20200817_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='books',
            new_name='title',
        ),
    ]
