# Generated by Django 2.2.14 on 2020-08-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20200817_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='title',
        ),
    ]
