# Generated by Django 2.2.14 on 2020-08-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_author_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='title',
        ),
    ]
