# Generated by Django 2.2.14 on 2020-08-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_remove_author_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
            preserve_default=False,
        ),
    ]
