# Generated by Django 2.2.14 on 2020-08-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20200818_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
