# Generated by Django 2.2.14 on 2020-08-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_author_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
    ]
